### PR TITLE
docs: add Flat Config example in README

### PR DESCRIPTION
**Pull request by koba04**
This PR adds documentation and an example for Flat Config with ESLint v9.

I've added documentation on configuring this plugin with Flat Config and updated the `sandbox` to use Flat Config and ESLint v9.

I've never touched plugin implementation and `dependencies` because this already works with Flat Config and ESLint v9.

I couldn't upgrade ESLint v9 because of issues with `eslint-docgen`, so I'll work on it at #79 and consider providing a better setup for Flat Config.

### CODE REVIEW

**Comment by anubra266** [comment]
@koba04 For the documentation, we'd want a legacy first approach. flat config is still the minority in the ecosystem.

**Comment by koba04** [comment]
> For the documentation, we'd want a legacy first approach. flat config is still the minority in the ecosystem.

Yeah, unfortunately, that is true. 
May I update the PR based on the strategy and legacy first approach?

**Comment by anubra266** [comment]
Yes feel free to go ahead @koba04

**Comment by koba04** [comment]
@anubra266 I've updated this PR to add Flat Config examples in README

**Review by anubra266 — APPROVED** [review]

**Comment by anubra266** [comment]
Thanks for working on this @koba04

**Pull request merged**
